paginate: 8
paginate_path: "/page:num/"

markdown: kramdown
highlighter: rouge
permalink: /:categories/:year/:month/:day/:title/

#Trigger rebuild
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

title: "CMALT Portfolio - Dr. Eric Martin PhD, MSc(Eng.), BSc(Eng.), BA, P.Eng. "
description: "Page design adapted from Millenial, a minimalist Jekyll theme by Paul Le. "
author: "Content and Design by Eric Martin"

baseurl: ""

future: true
