# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'G-JF4HT1HW8E'

#menu:
#- {name: 'Interesting Facts',  url: 'facts'}
#- {name: 'Learning Resources', url: 'resources'}
#- {name: 'Sample Posts',       url: 'sample-posts'}
#- {name: 'Documentation',      url: 'documentation'}
#- {name: 'About',              url: 'about'}
#- {name: 'Contact',            url: 'contact'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'link', link: 'https://www.gre.ac.uk/people/rep/faculty-of-engineering-and-science/eric-martin'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/ejmartinphd'}
- {icon: 'dot-circle-o', link: 'https://orcid.org/0009-0005-9135-3382'}
- {icon: 'envelope', link: 'mailto:e.martin@greenwich.ac.uk'}
- {icon: 'bomb', link: '/404.html'}

# Customize site text
#pagination:
 # next_page: 'Newer'
 # previous_page: 'Older'

#sharing_button_prompt: 'Feel free to share!'

#related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
